# Utiliser une image de base Nginx
FROM nginx:alpine

# Copier les fichiers HTML, CSS et JS dans le répertoire de Nginx
COPY . /usr/share/nginx/html

# Exposer le port sur lequel Nginx va s'exécuter
EXPOSE 80